# Site settings
title: DOSE (Et Si On Discutait ?)
email: contact@corentin-hatte.eu
description: >-
  Un blog qui pousse à la discussion et à la réflexion
baseurl: ""
url: ""
twitter_username: viki53
language: "fr"
timezone: "Europe/Paris"
encoding: "utf-8"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

sass:
  sass_dir: _sass
  style: compressed

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - categories
  layout: archive
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    category: '/blog/categorie/:name/'

paginate: 10
excerpt_separator: "---"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
